### PR TITLE
Removed restrictions on the type of character allowed to match mentions

### PR DESCRIPTION
**Pull request by fredck**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Other: Mentions can now be matched by any character typed. Closes ckeditor/ckeditor5#6398.

### CODE REVIEW

**Comment by fredck** [comment]
The Travis checks seem to have failed because of issues not related to this PR. Got all tests green on my side.

**Comment by fredck** [comment]
Force-pushed a rebase over v18.0.0.

**Comment by dunncl15** [comment]
@fredck is there a timeline for merging this update?

**Comment by Reinmar** [comment]
We're looking into it right now, @dunncl15.

**Pull request merged**
