### PR TITLE
T/37:  The mention UI should prefer position below the caret. 

### LINKED ISSUE #37: The autocompletion panel should prefer the south positon
Instead, it prefers the north position:

image

### PR DESCRIPTION
**Pull request by jodator**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: The mention UI should prefer position below the caret. Closes #37.

---

### Additional information
* The only change that was preserved is the order of position returned by `getBalloonPositionData()`

* ~I've added some padding text to the manual test to overcome [short body problem](https://github.com/ckeditor/ckeditor5-mention/issues/37#issuecomment-481653792).~
* ~It does look OK now in the docs:~

~Selection_298~

### CODE REVIEW

**Comment by oleq** [comment]
TBH, this looks like a bug to me:

image

I agree that we should prefer the positions below the caret, but if that means the panel will stick out of the editor even though there is enough space to accommodate it inside it, it's a bad practice IMO. 

We don't know what's below the editor, it could be some form or other application UI that matters to the user. Or the editor could be in a modal, and since we're using a floating panel stored directly in `<body>`, it would position correctly with respect to the editor, but it would stick out of the modal. And there's no way for developers to change that behavior. 

The rule of thumb should be that the editor keeps its elements within the editable whenever possible because this is the only space we can safely use. The rest is a gamble for us because it depends on the integration. 

So I'm for changing the order of prefered panel positions but restoring the limiter back to editable to stay on the safe side. Even though, in some cases, it will look like this

image

it is still better IMO than the other way around because it's not CKEditor territory we'd using.

**Comment by mlewand** [comment]
Restoring @oleq as reviewier as I didn't noticed that changes requested in a previous comment are not applied yet.

**Comment by jodator** [comment]
OK guys, we need to do something with this one: either we incorporate this PR (in line with @Reinmar suggestions) or simply close it as previously the limiter was set to the editable area as @oleq [proposed](https://github.com/ckeditor/ckeditor5-mention/pull/52#issuecomment-484852365).

**Comment by mlewand** [comment]
Just to throw 2 cents here, I'd second to that it makes more sense to put dropdown inside of editor region whenever possible.

**Comment by Reinmar** [comment]
@oleq's arguments make a lot of sense. I still have some doubts, but I retract my vote (including my ticket).

**Comment by jodator** [comment]
> @oleq's arguments make a lot of sense. I still have some doubts, but I retract my vote (including my ticket).

So I'll cleanup this PR so only "prefer south" position will be preserved.

**Comment by jodator** [comment]
@oleq OK I've revamped the PR and made sure that mention balloon would prerfer south positions.

**Pull request merged**
