### PR TITLE
Removed the confirmation of mention selection by using space

### LINKED ISSUE #6394: Mention: do not confirm selection on "space"
## 📝 Provide a description of the improvement

Currently, it is cumbersome to simply type text that uses the mention marker but is not in the mention list, in some cases.

For example, suppose this:

*   My app loads just the last 500 issue numbers of CKEditor 5 in the mention list.
*   Let's say we have 1200 issue is total -> therefore issues from 700 to 1200 are loaded.
*   My app uses hash (#) as the marker to mention issues.
*   I want to mention issue 1. I type `#1`.
    *   At this point, the mention list is shown. As the list is filtered by what I typed, I see issues 1000, 1001, 1002... with issue 1000 pre-selected.
*   I want to continuer typing after `#1`, so I hit `space`.
    *   **Issues**: my typed `#1` is replaced with `#1000`. That's because `space` was used to confirm my selection in the list, which is clearly not what I wanted.

This seems to be caused by this line, which tells me that even `tab` could be used to confirm my select :thinking:   
https://github.com/ckeditor/ckeditor5-mention/blob/9a514ccb0dc8b595100fd4459a82fa67cc329d1d/src/mentionui.js#L124

I propose to allow confirming the selected item by using the `enter` key, exclusively.

## 📃 Other details

*   CKEditor version: v17.0.0
*   Installed CKEditor plugins: mention

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by fredck**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Other: The `space` and `tab` keys are not anymore used to confirm a mention selection from the list. Closes ckeditor/ckeditor5#6394.

### CODE REVIEW

**Comment by fredck** [comment]
The Travis checks seem to have failed because of issues not related to this PR. Got all tests green on my side.

**Comment by fredck** [comment]
Force-pushed a rebase over v18.0.0.

**Comment by fredck** [comment]
The `tab` key is indeed a valid key for mention confirmation as it is commonly used in programming IDEs for that purpose. Additionally, unlike `space`, `tab` is mostly never used as a common typing key after mention text. 

Because of the above I've reverted the changes related to the `tab` key, reducing the scope of the changes to the `space` key only.

**Comment by fredck** [comment]
Force-pushed a rebase over v19.0.0.

**Comment by zadam** [comment]
It would be great to see this fix in the next release!

**Comment by fredck** [comment]
The PR has been moved to ckeditor/ckeditor5#7306. 

For those interested, be sure to add :+1: and further feedback there.

**Pull request closed without merging**
